ErlOpts = proplists:get_value(erl_opts, CONFIG),

JsonModuleStr = case os:getenv("OAUTH2_JWT_TOKEN_JSON_MODULE") of
    Value when erlang:is_list(Value), erlang:length(Value) > 0 ->
        Value;
    _ ->
        "jsx"
end,

JsonModule = erlang:list_to_atom(JsonModuleStr),

NewErlOpts = [ {d, 'OAUTH2_JWT_TOKEN_JSON_MODULE', JsonModule} | ErlOpts],
lists:keystore(erl_opts, 1, CONFIG, {erl_opts, NewErlOpts}).
